import java.applet.*;
import java.awt.color.*;
/*
 * Scenario : XXXX
 * Steps count : XX
 * Test Cases count : XX
 * Generation Date : XX/XX/XX XX:XX:XX
 * Generation Mode : Development Mode
 */
public class Test {

    /*
     * ## Step ID : XXXX ## Step Text : Lorem ipsum dolor sit amet, consectetur
     * adipiscing elit, tempor incididunt ut labore et dolore magna aliqua. Ut
     * enim ad minim veniam, quis nostrud exercitation ullamco. 
     * ## Step Type : Type 
     * ## Step Test Case : Test Case ID
     */
    public void method1() {

	// TODO
	Platform.virifyResponseStatus("9090"); // generated by RTMT 
    }

    /*
     * ## Step ID : XXXX 
     * ## Step Text : Lorem ipsum dolor sit amet, consectetur
     * adipiscing elit, tempor incididunt ut labore et dolore magna aliqua. Ut
     * enim ad minim veniam, quis nostrud exercitation ullamco. 
     * ## Step Type : Type 
     * ## Step Test Case : Test Case ID
     */
    public void method2() {

	// TODO
	Platform.virifyResponseStatus("8080"); // generated by RTMT
    }
}
